### PR TITLE
Move to gsw

### PR DESCRIPTION
**Pull request by callumrollo**
This resolves Issue #20 

The move to gsw would remove a deprecated dependency and modernise the package. This is an essential step if we eventually want to get this on pypi/conda-forge.

Most of the changes went without a problem. There are a couple of hiccups: the depth produced by gsw differs very slightly (sub mm scale) from that in seawater. Consequently all tests against old data fail. To get past this, I have temporarily dropped the depth dimension before testing results against the test data, so we can focus on the variables that are actually changing. These are:

salinity
potential_density
density
potential_temperature
distance_over_ground

Of these, only distance_over_ground is substantially different. It increases by a factor of around 1.7

### CODE REVIEW

**Comment by callumrollo** [comment]
depth

density


potential_density

potential_temperature

salinity

distance_over_ground

All these images are from the **example-seaexplorer-legato-flntu-arod-ad2cp** dataset

**Comment by jklymak** [comment]
1.7 is the difference between km and nautical miles, so I think that is just a  setting.  We should be using km, I would argue.

**Comment by callumrollo** [comment]
That was what I suspected. gsw outputs m by default. I divided by 1000 to get km. As the gsw distance is 1.7 * the seatwater distance, that would suggest seawater was outputting nautical miles. Which is odd as I though it should do km by default.

I'll look into it

**Comment by callumrollo** [comment]
Are the changes in the other variables small enough to be acceptable? Are there further tests we should do before a switch to gsw?

**Comment by jklymak** [comment]
I think we are testing that the process works, and that values don't change unexpectedly.  Here we expect a change, and indeed you saw a sizeable change in one variable.  So I'd say the tests are doing their job, and its OK to change the "truth" files once we are happy with them.

**Comment by callumrollo** [comment]
Found the issue with distance. gsw.distance takes (lon, lat) where seawater.dist takes (lat, lon). Corrected now

distance_over_ground

**Comment by callumrollo** [comment]
I'm happy with the small changes in the other variables. Shall I update the testcase data with gsw output?

**Comment by jklymak** [comment]
Thats fine with me!  Thanks!

**Comment by callumrollo** [comment]
Done :) please merge once the tests have passed

**Comment by richardsc** [comment]
Late to this party but all looks good to me.

**Pull request merged**
